services:
    pharmacy_catalog_node1:
      container_name: pharmacy_catalog_node1
      build:
        dockerfile: Dockerfile
      command:
        - "make"
        - "run"
      restart: always
      env_file:
        - .env
      networks:
        - pharmacy_catalog

    pharmacy_catalog_node2:
      container_name: pharmacy_catalog_node2
      build:
        dockerfile: Dockerfile
      command:
        - "make"
        - "run"
      restart: always
      env_file:
        - .env
      networks:
        - pharmacy_catalog

    pharmacy_catalog_db:
      image: postgres:16.2
      container_name: pharmacy_catalog_db
      restart: always
      shm_size: 128mb
      env_file:
        - .docker.env
      environment:
        POSTGRES_PASSWORD: POSTGRES_PASSWORD
        POSTGRES_USER: POSTGRES_USER
        POSTGRES_DB: POSTGRES_DB
      volumes:
        - pharmacy_catalog_db:/var/lib/postgresql/data
      networks:
        - pharmacy_catalog

    nginx_catalog:
      image: nginx:latest
      volumes:
        - /opt/homebrew/etc/nginx/catalog_nginx.conf:/etc/nginx/nginx.conf
      depends_on:
        - pharmacy_catalog_node1
        - pharmacy_catalog_node2
      networks:
        - pharmacy_catalog
        - pharmacy_auth_gateway

volumes:
  pharmacy_catalog_db:
    driver: local

networks:
  pharmacy_catalog:
    driver: bridge
  pharmacy_auth_gateway:
    external: true
