"""create tags table

Revision ID: 46b0688455be
Revises: 4caaf9a86218
Create Date: 2024-10-22 17:37:11.522588

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "46b0688455be"
down_revision: Union[str, None] = "4caaf9a86218"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags",
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_tags")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tags")
    # ### end Alembic commands ###
